"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.FONT_SCALE = exports.IS_IOS = exports.MENU_TRANSFORM_ORIGIN_TOLERENCE = exports.SPRING_CONFIGURATION_MENU = exports.SPRING_CONFIGURATION = exports.HOLD_ITEM_SCALE_DOWN_DURATION = exports.HOLD_ITEM_SCALE_DOWN_VALUE = exports.HOLD_ITEM_TRANSFORM_DURATION = exports.MENU_CONTAINER_WIDTH = exports.MENU_WIDTH = exports.WINDOW_WIDTH = exports.WINDOW_HEIGHT = exports.CONTEXT_MENU_STATE = void 0;

var _reactNative = require("react-native");

const HOLD_ITEM_TRANSFORM_DURATION = 150;
exports.HOLD_ITEM_TRANSFORM_DURATION = HOLD_ITEM_TRANSFORM_DURATION;
const HOLD_ITEM_SCALE_DOWN_VALUE = 0.95;
exports.HOLD_ITEM_SCALE_DOWN_VALUE = HOLD_ITEM_SCALE_DOWN_VALUE;
const HOLD_ITEM_SCALE_DOWN_DURATION = 210;
exports.HOLD_ITEM_SCALE_DOWN_DURATION = HOLD_ITEM_SCALE_DOWN_DURATION;
const SPRING_CONFIGURATION = {
  damping: 33,
  mass: 1.03,
  stiffness: 500,
  restDisplacementThreshold: 0.001,
  restSpeedThreshold: 0.001
};
exports.SPRING_CONFIGURATION = SPRING_CONFIGURATION;
const SPRING_CONFIGURATION_MENU = {
  damping: 39,
  mass: 1.09,
  stiffness: 500,
  restDisplacementThreshold: 0.001,
  restSpeedThreshold: 0.001
};
exports.SPRING_CONFIGURATION_MENU = SPRING_CONFIGURATION_MENU;
var CONTEXT_MENU_STATE;
exports.CONTEXT_MENU_STATE = CONTEXT_MENU_STATE;

(function (CONTEXT_MENU_STATE) {
  CONTEXT_MENU_STATE[CONTEXT_MENU_STATE["UNDETERMINED"] = 0] = "UNDETERMINED";
  CONTEXT_MENU_STATE[CONTEXT_MENU_STATE["ACTIVE"] = 1] = "ACTIVE";
  CONTEXT_MENU_STATE[CONTEXT_MENU_STATE["END"] = 2] = "END";
})(CONTEXT_MENU_STATE || (exports.CONTEXT_MENU_STATE = CONTEXT_MENU_STATE = {}));

const {
  height: WINDOW_HEIGHT,
  width: WINDOW_WIDTH
} = _reactNative.Dimensions.get('screen');

exports.WINDOW_WIDTH = WINDOW_WIDTH;
exports.WINDOW_HEIGHT = WINDOW_HEIGHT;
const MENU_CONTAINER_WIDTH = 100;
exports.MENU_CONTAINER_WIDTH = MENU_CONTAINER_WIDTH;
const MENU_WIDTH = WINDOW_WIDTH * 60 / 100;
exports.MENU_WIDTH = MENU_WIDTH;
const MENU_TRANSFORM_ORIGIN_TOLERENCE = 10;
exports.MENU_TRANSFORM_ORIGIN_TOLERENCE = MENU_TRANSFORM_ORIGIN_TOLERENCE;
const IS_IOS = _reactNative.Platform.OS === 'ios';
exports.IS_IOS = IS_IOS;

const FONT_SCALE = _reactNative.Dimensions.get('screen').fontScale;

exports.FONT_SCALE = FONT_SCALE;
//# sourceMappingURL=constants.js.map