"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.MENU_TEXT_DESTRUCTIVE_COLOR_DARK = exports.MENU_TEXT_DESTRUCTIVE_COLOR_LIGHT = exports.MENU_TEXT_DARK_COLOR = exports.MENU_TEXT_LIGHT_COLOR = exports.MENU_TITLE_COLOR = exports.BORDER_DARK_COLOR = exports.BORDER_LIGHT_COLOR = void 0;
const BORDER_LIGHT_COLOR = 'rgba(0, 0, 0, 0.1)';
exports.BORDER_LIGHT_COLOR = BORDER_LIGHT_COLOR;
const BORDER_DARK_COLOR = 'rgba(255, 255, 255, 0.1)';
exports.BORDER_DARK_COLOR = BORDER_DARK_COLOR;
const MENU_TITLE_COLOR = 'gray';
exports.MENU_TITLE_COLOR = MENU_TITLE_COLOR;
const MENU_TEXT_LIGHT_COLOR = 'rgba(0, 0, 0, 1)';
exports.MENU_TEXT_LIGHT_COLOR = MENU_TEXT_LIGHT_COLOR;
const MENU_TEXT_DARK_COLOR = 'rgb(255, 255, 255)';
exports.MENU_TEXT_DARK_COLOR = MENU_TEXT_DARK_COLOR;
const MENU_TEXT_DESTRUCTIVE_COLOR_LIGHT = 'rgb(255, 59,48)';
exports.MENU_TEXT_DESTRUCTIVE_COLOR_LIGHT = MENU_TEXT_DESTRUCTIVE_COLOR_LIGHT;
const MENU_TEXT_DESTRUCTIVE_COLOR_DARK = 'rgb(255, 69,58)';
exports.MENU_TEXT_DESTRUCTIVE_COLOR_DARK = MENU_TEXT_DESTRUCTIVE_COLOR_DARK;
//# sourceMappingURL=constants.js.map